### ISSUE TITLE
Misinformation about number of quotes

### ISSUE THREAD

**Issue by coolshaurya** [4skinSkywalker/Database-Quotes-JSON#7]
As per your description and README the are 5000+ quotes but there are only 1640 quotes in total. So will you please change both the description and README to say any of the following -

- 1500+ quotes
- 1600+ quotes
- 1640 quotes

**Comment by 4skinSkywalker** [comment]
This is the way of asking! ;)

**Comment by coolshaurya** [comment]
You should update the description too ! It still says 5000 + quotes

**Comment by 4skinSkywalker** [comment]
Thanks!
